# Generated by Django 2.2.5 on 2019-09-11 03:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Unknown')], default='u', max_length=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('u', 'Unknown')], default='u', max_length=1),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('b', 'Baby'), ('y', 'Young'), ('a', 'Adult'), ('s', 'Senior')], max_length=7),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Unknown')], max_length=5),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('u', 'Unknown')], max_length=10),
        ),
    ]
