# Generated by Django 2.2 on 2020-03-25 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name',
                 models.CharField(blank=True, default='', max_length=50)),
                ('image_filename',
                 models.CharField(blank=True, default='', max_length=100)),
                ('breed', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(
                    choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Unknown')],
                    default='u', max_length=2)),
                ('size', models.CharField(
                    choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'),
                             ('xl', 'Extra Large'), ('u', 'Unknown')],
                    default='u', max_length=2)),
                ],
            ),
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True,
                                         choices=[('b', 'Baby'), ('y', 'Young'),
                                                  ('a', 'Adult'),
                                                  ('s', 'Senior')], default='',
                                         max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'),
                                                                 (
                                                                 'f', 'Female'),
                                                                 ('u',
                                                                  'Unknown')],
                                            default='', max_length=4)),
                ('size', models.CharField(blank=True, choices=[('s', 'Small'),
                                                               ('m', 'Medium'),
                                                               ('l', 'Large'), (
                                                               'xl',
                                                               'Extra Large'), (
                                                               'u', 'Unknown')],
                                          default='', max_length=10)),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='userpref',
                                   to=settings.AUTH_USER_MODEL)),
                ],
            ),
        migrations.CreateModel(
            name='UserDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[('l', 'Liked'), ('d', 'Disliked'),
                             ('u', 'Undecided')], default='u', max_length=1)),
                ('dog', models.ForeignKey(null=True,
                                          on_delete=django.db.models.deletion.CASCADE,
                                          related_name='users_dog',
                                          related_query_name='user_dogs_query',
                                          to='pugorugh.Dog')),
                ('user', models.ForeignKey(null=True,
                                           on_delete=django.db.models.deletion.CASCADE,
                                           related_name='dogs_user',
                                           related_query_name='dogs_user_query',
                                           to=settings.AUTH_USER_MODEL)),
                ],
            ),
        ]
