# Generated by Django 2.2.5 on 2019-10-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0004_auto_20190922_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image_filename',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
