# Generated by Django 2.2.7 on 2019-12-14 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pugorugh', '0007_auto_20191212_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdog',
            name='dog',
        ),
        migrations.AddField(
            model_name='userdog',
            name='dog',
            field=models.ManyToManyField(related_name='users_dog', related_query_name='user_dog', to='pugorugh.Dog'),
        ),
        migrations.RemoveField(
            model_name='userdog',
            name='user',
        ),
        migrations.AddField(
            model_name='userdog',
            name='user',
            field=models.ManyToManyField(related_name='dogs_user', related_query_name='dog_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
