# Generated by Django 2.2.7 on 2019-12-15 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0009_auto_20191215_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprefs', to=settings.AUTH_USER_MODEL),
        ),
    ]
